# Generated by Django 5.0.6 on 2024-06-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_Name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Admin_role', models.CharField(max_length=50)),
            ],
        ),
    ]
