# Generated by Django 5.0.6 on 2024-06-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(default='default_name', max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name_of_the_customer', models.CharField(max_length=50)),
                ('Delivery_Address', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('Phone_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('BoyID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Vehicle', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'deliveryboy',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('PromoCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Percentage', models.IntegerField()),
                ('MinOrderValue', models.IntegerField()),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField()),
                ('ItemID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('OrderDate', models.DateTimeField(blank=True, null=True)),
                ('Mode_of_payment', models.CharField(max_length=50)),
                ('Trip_Status', models.IntegerField()),
                ('CustomerID', models.IntegerField()),
                ('PartnerID', models.IntegerField()),
                ('VendorID', models.IntegerField()),
                ('CategoryID', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Name_of_the_item', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Description', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
    ]
