# Generated by Django 5.0.6 on 2024-06-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_admin_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Admin_role',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
