# Generated by Django 5.0.6 on 2024-06-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_admin_admin_role_alter_admin_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Admin_role',
        ),
    ]
